import 'dart:typed_data';

import 'package:cryptography/cryptography.dart' hide CipherState;
import 'package:flutter_test/flutter_test.dart';
import 'package:muse_desktop_companion/src/gadget/noise_xx.dart';

Uint8List _hex(String s) {
  final out = Uint8List(s.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(s.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

String _hexOf(Uint8List bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

// Fixed-key transcript generated by the reference Python SDK
// (NoiseXXInitiator/Responder with static X25519 keys). The Dart port must
// reproduce it byte-for-byte; verified by running both sides.
const _initEPriv =
    'a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba4499a4';
const _initEPub =
    '8ba76a15dfdfb6a2751cfe5a2823f1c0d2ade1f9295913441345506cb790803c';
const _initSPriv =
    '1111111111111111111111111111111111111111111111111111111111111111';
const _initSPub =
    '7b4e909bbe7ffe44c465a220037d608ee35897d31ef972f07f74892cb0f73f13';
const _respEPriv =
    '2222222222222222222222222222222222222222222222222222222222222222';
const _respEPub =
    '0faa684ed28867b97f4a6a2dee5df8ce974e76b7018e3f22a1c4cf2678570f20';
const _respSPriv =
    '3333333333333333333333333333333333333333333333333333333333333333';
const _respSPub =
    '7b0d47d93427f8311160781c7c733fd89f88970aef490d8aa0ee19a4cb8a1b14';
const _goldenMsg2 =
    '0faa684ed28867b97f4a6a2dee5df8ce974e76b7018e3f22a1c4cf2678570f20'
    '2f992edac4ee1ca35dd3bec98eed6b2da5f25433f8dac913fac2109c04970fe3f'
    '933bb1ceb7b888462ae1776f247e61bec291456e1a2e0b5b3fe6a84f219bb95';
const _goldenMsg3 =
    '523a61d92db61ecd817a22daf7d27484ff726ef50b6649de898e6fc3381ec42'
    '1196079ccd92359d994ce37d5994604a368f91b80fbf594a9d5c6c8701db3fdbc';
const _goldenHash =
    '32367cfa8bec412bf80a2ce7566a952ea42e9a24fa0afd83f9791e996c3ca43e';
const _goldenProbeI2R = 'b313c0c93fcdd29bd2e3b4ebfb8c3100a2ed24cdb72b48';
const _goldenProbeR2I = '091b145a74c9f64809edca8f048ea53a02016964315de9';

void main() {
  group('nonce iv', () {
    test('builds the 4-zero-plus-uint64 layout', () {
      expect(buildNonceIv(0), List.filled(12, 0));
      expect(buildNonceIv(1).sublist(11), [1]);
      expect(buildNonceIv(0x0102030405060708).sublist(4),
          [1, 2, 3, 4, 5, 6, 7, 8]);
    });

    test('rejects out-of-range nonces', () {
      expect(() => buildNonceIv(-1), throwsA(isA<NoiseProtocolError>()));
    });
  });

  group('cipher state', () {
    test('passes plaintext through before a key is set', () async {
      final cipher = CipherState();
      expect(cipher.hasKey(), isFalse);
      final data = Uint8List.fromList([1, 2, 3]);
      expect(await cipher.encryptWithAd(Uint8List(0), data), data);
      expect(await cipher.decryptWithAd(Uint8List(0), data), data);
    });

    test('round-trips with associated data', () async {
      final cipher = CipherState();
      cipher.initializeKey(Uint8List.fromList(List.filled(32, 9)));
      final ad = Uint8List.fromList([5, 6]);
      final plain = Uint8List.fromList([1, 2, 3, 4]);
      final encrypted = await cipher.encryptWithAd(ad, plain);
      expect(encrypted.length, plain.length + 16);
      // A fresh cipher with the same key restarts at nonce 0 and decrypts.
      final decipher = CipherState();
      decipher.initializeKey(Uint8List.fromList(List.filled(32, 9)));
      expect(await decipher.decryptWithAd(ad, encrypted), plain);
    });

    test('wrong associated data fails and poisons', () async {
      final cipher = CipherState();
      cipher.initializeKey(Uint8List.fromList(List.filled(32, 9)));
      final encrypted = await cipher.encryptWithAd(
          Uint8List.fromList([1]), Uint8List.fromList([2]));
      final decipher = CipherState();
      decipher.initializeKey(Uint8List.fromList(List.filled(32, 9)));
      await expectLater(
          decipher.decryptWithAd(Uint8List.fromList([9]), encrypted),
          throwsA(isA<NoiseProtocolError>()));
      await expectLater(
          decipher.decryptWithAd(Uint8List.fromList([1]), encrypted),
          throwsA(isA<NoiseProtocolError>()));
    });

    test('rejects short keys', () {
      expect(() => CipherState().initializeKey(Uint8List(16)),
          throwsA(isA<NoiseProtocolError>()));
    });
  });

  group('handshake', () {
    test('initiator and responder agree on transport keys', () async {
      final initiator = NoiseXXInitiator();
      final responder = NoiseXXResponder();
      await initiator.initialize();
      await responder.initialize();

      final msg1 = await initiator.writeMessage1();
      expect(msg1.length, dhKeyLen);
      final msg2 = await responder.readMessage1AndWriteMessage2(msg1);
      final payload = await initiator.readMessage2(msg2);
      expect(payload, isEmpty);
      final msg3 = await initiator.writeMessage3();
      await responder.readMessage3(msg3);

      expect(initiator.handshakeHash(), responder.handshakeHash());
      // The initiator learned the responder's static key.
      expect(initiator.remoteStaticPublicKey(), isNotNull);

      final (iSend, iRecv) = await initiator.split();
      final (rSend, rRecv) = await responder.split();
      final probe = Uint8List.fromList('transport check'.codeUnits);
      final toResponder = await iSend.encryptWithAd(Uint8List(0), probe);
      expect(await rRecv.decryptWithAd(Uint8List(0), toResponder), probe);
      final toInitiator = await rSend.encryptWithAd(Uint8List(0), probe);
      expect(await iRecv.decryptWithAd(Uint8List(0), toInitiator), probe);
    });

    test('fixed keys replay a deterministic handshake', () async {
      // Two real key pairs, generated once and reused across both runs.
      Future<NoiseKeyPair> snap() async {
        final fresh = await X25519().newKeyPair();
        final pub = await fresh.extractPublicKey();
        final priv = await fresh.extractPrivateKeyBytes();
        return fixedX25519KeyPair(
            Uint8List.fromList(priv), Uint8List.fromList(pub.bytes));
      }

      final initKeys = [await snap(), await snap()];
      final respKeys = [await snap(), await snap()];

      Future<List<Uint8List>> runOnce() async {
        var i = 0;
        var r = 0;
        final initiator =
            NoiseXXInitiator(keyPairFactory: () async => initKeys[i++]);
        final responder =
            NoiseXXResponder(keyPairFactory: () async => respKeys[r++]);
        await initiator.initialize();
        await responder.initialize();
        final msg1 = await initiator.writeMessage1();
        final msg2 = await responder.readMessage1AndWriteMessage2(msg1);
        await initiator.readMessage2(msg2);
        final msg3 = await initiator.writeMessage3();
        await responder.readMessage3(msg3);
        return [msg1, msg2, msg3, initiator.handshakeHash()];
      }

      final first = await runOnce();
      expect(first[0], initKeys[0].publicKeyBytes);
      final second = await runOnce();
      for (var i = 0; i < first.length; i++) {
        expect(second[i], first[i]);
      }
    });

    test('reproduces the reference Python transcript byte-for-byte',
        () async {
      final initKeys = [
        await fixedX25519KeyPair(_hex(_initEPriv), _hex(_initEPub)),
        await fixedX25519KeyPair(_hex(_initSPriv), _hex(_initSPub)),
      ];
      final respKeys = [
        await fixedX25519KeyPair(_hex(_respEPriv), _hex(_respEPub)),
        await fixedX25519KeyPair(_hex(_respSPriv), _hex(_respSPub)),
      ];
      var i = 0;
      var r = 0;
      final initiator =
          NoiseXXInitiator(keyPairFactory: () async => initKeys[i++]);
      final responder =
          NoiseXXResponder(keyPairFactory: () async => respKeys[r++]);
      await initiator.initialize();
      await responder.initialize();
      final msg1 = await initiator.writeMessage1();
      expect(_hexOf(msg1), _initEPub);
      final msg2 = await responder.readMessage1AndWriteMessage2(msg1);
      expect(_hexOf(msg2), _goldenMsg2);
      await initiator.readMessage2(msg2);
      final msg3 = await initiator.writeMessage3();
      expect(_hexOf(msg3), _goldenMsg3);
      await responder.readMessage3(msg3);
      expect(_hexOf(initiator.handshakeHash()), _goldenHash);
      expect(_hexOf(responder.handshakeHash()), _goldenHash);

      final (iSend, iRecv) = await initiator.split();
      final (rSend, rRecv) = await responder.split();
      final probeA = Uint8List.fromList('probe-A'.codeUnits);
      final probeB = Uint8List.fromList('probe-B'.codeUnits);
      final encA = await iSend.encryptWithAd(Uint8List(0), probeA);
      expect(_hexOf(encA), _goldenProbeI2R);
      expect(await rRecv.decryptWithAd(Uint8List(0), encA), probeA);
      final encB = await rSend.encryptWithAd(Uint8List(0), probeB);
      expect(_hexOf(encB), _goldenProbeR2I);
      expect(await iRecv.decryptWithAd(Uint8List(0), encB), probeB);
    });

    test('short message 2 kills the handshake', () async {
      final initiator = NoiseXXInitiator();
      await initiator.initialize();
      await initiator.writeMessage1();
      await expectLater(initiator.readMessage2(Uint8List(10)),
          throwsA(isA<NoiseProtocolError>()));
      await expectLater(initiator.writeMessage3(),
          throwsA(isA<NoiseProtocolError>()));
    });

    test('low-order responder key is rejected', () async {
      final initiator = NoiseXXInitiator();
      await initiator.initialize();
      await initiator.writeMessage1();
      // re = all zeros (low-order), rest padded to minimum length.
      await expectLater(initiator.readMessage2(Uint8List(minMsg2Len)),
          throwsA(isA<NoiseProtocolError>()));
    });

    test('wrong-phase calls throw', () async {
      final initiator = NoiseXXInitiator();
      await expectLater(
          initiator.writeMessage1(), throwsA(isA<NoiseProtocolError>()));
      await initiator.initialize();
      await expectLater(initiator.readMessage2(Uint8List(minMsg2Len)),
          throwsA(isA<NoiseProtocolError>()));
    });

    test('responder rejects short messages', () async {
      final responder = NoiseXXResponder();
      await responder.initialize();
      await expectLater(
          responder.readMessage1AndWriteMessage2(Uint8List(5)),
          throwsA(isA<NoiseProtocolError>()));
    });

    test('tampered message 3 fails authentication', () async {
      final initiator = NoiseXXInitiator();
      final responder = NoiseXXResponder();
      await initiator.initialize();
      await responder.initialize();
      final msg1 = await initiator.writeMessage1();
      final msg2 = await responder.readMessage1AndWriteMessage2(msg1);
      await initiator.readMessage2(msg2);
      final msg3 = await initiator.writeMessage3();
      msg3[msg3.length - 1] ^= 0xff;
      await expectLater(
          responder.readMessage3(msg3), throwsA(isA<NoiseProtocolError>()));
    });
  });
}
